---
- name: Upgrade packages, install development tools, upgrade kernel, and reboot servers if needed
  hosts: centos7_servers, almalinux_servers, rockylinux_servers
  become: yes
  tasks:
    - name: Update package cache
      package:
        name: '*'
        state: latest
      register: update_result

    - name: Install development tools
      package:
        name: '@development'
        state: present

    - name: Check if kernel package is updated
      set_fact:
        kernel_updated: "{{ update_result | json_query('package_update.kernel') | default([]) }}"

    - name: Upgrade kernel to the latest version
      package:
        name: kernel
        state: latest
        update_cache: yes
      when: kernel_updated | length > 0

    - name: Reboot servers if kernel updated
      reboot:
      when: kernel_updated | length > 0